language: csharp
solution: eWolfLabs/eWolfLabs.sln

install:
  - nuget restore eWolfLabs/eWolfLabs.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release eWolfLabs/eWolfLabs.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe eWolfLabs\BasicUnitTests\CalculatorUnitTests\bin\Release\CalculatorUnitTests.dll
  