language: csharp
solution: eWolfLabs/eWolfLabs.sln

install:
  - nuget restore eWolfLabs/eWolfLabs.sln
  - nuget install NUnit.Runners -Version 3.8.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release eWolfLabs/eWolfLabs.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe eWolfLabs/ExamplesUnitTests/bin/Release/ExamplesUnitTests.dll
#  - mono ./testrunner/NUnit.Runners.3.8.0/tools/nunit-console.exe eWolfLabs/BasicUnitTests/CalculatorUnitTests/bin/Release/CalculatorUnitTests.dll
#  - mono ./testrunner/NUnit.Runners.3.8.0/tools/nunit-console.exe eWolfLabs/UntestableCode/UntestableCodeTests/bin/Release/UntestableCodeTests.dll