language: csharp
solution: eWolfLabs/eWolfLabs.sln

install:
  - nuget restore eWolfLabs/eWolfLabs.sln
  - nuget install NUnit.Runners -Version 2.6.6 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release eWolfLabs/eWolfLabs.sln
  - mono ./testrunner/NUnit.Runners.2.6.6/tools/nunit-console.exe eWolfLabs/BasicUnitTests/CalculatorUnitTests/bin/Release/CalculatorUnitTests.dll
  - mono ./testrunner/NUnit.Runners.2.6.6/tools/nunit-console.exe eWolfLabs/ExamplesUnitTests/bin/Release/ExamplesUnitTests.dll
  - mono ./testrunner/NUnit.Runners.2.6.6/tools/nunit-console.exe eWolfLabs/UntestableCode/UntestableCodeTests/bin/Release/UntestableCodeTests.dll
 
  